import type { Metadata } from "next";
import { inter } from '@/app/ui/fonts';
import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Alashmedia.kz",
  description: "Generated by Alash Media KZ",
  icons: {
    icon: "/logo.png",
  }
};

export default async function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
  
}>) {
    
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body
        className={`${inter.className} antialiased`} suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
