import type { Metadata } from "next";
import "@/app/globals.css";
import { hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from "next-intl/server";
import Header from "../ui/components/header";
import Subheader from "../ui/components/subheader";
import Footer from "../ui/components/footer";
export const metadata: Metadata = {
  title: "Alashmedia.kz",
  description: "Generated by Alash Media KZ",
  icons: {
    icon: "/favicon.ico",
  },
};

type LocaleLayoutProps = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout(props: LocaleLayoutProps) {
  const { children, params } = props;
  const { locale } = await params;
  //const locale = await getLocale();
  
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <NextIntlClientProvider messages={messages}>
      <Header />
      <Subheader />
      <main>{children}</main>
      <Footer />
    </NextIntlClientProvider>
  );
}

