import type { Metadata } from "next";
import { inter } from '@/app/ui/fonts';
import "@/app/globals.css";
import Head from "next/head";
import {hasLocale} from 'next-intl';
import { notFound } from 'next/navigation';
import {routing} from '@/i18n/routing';
import {NextIntlClientProvider} from 'next-intl';
import { getMessages } from "next-intl/server";
import Header from "../ui/components/header";
import Subheader from "../ui/components/subheader";
import Footer from "../ui/components/footer";
import SearchContent from "../ui/components/searchcontent";
import Pagination from "../ui/dashboard/pagination";
import { fetchSearchContentPages } from "../lib/data";

export const metadata: Metadata = {
  title: "Alashmedia.kz",
  description: "Generated by Alash Media KZ",
  icons: {
    icon: "/favicon.ico",
  }
};

export default async function LocaleLayout({
  children,
  params,
  searchParams,
  
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
  searchParams?: Promise<{
    title?: string;
    searchquery: string;
    page?: string;
    pathName?: string;
    
    }>
  
  
}) {
  const {locale} = await params; 
  //const locale = await getLocale();
       
  //const searchSlug = searchParams?.title?.toString() || '';
  const tquery = (await searchParams)?.searchquery || '';
  const tcurrentPage = Number((await searchParams)?.page) || 1
  const totalPages = await fetchSearchContentPages(tquery);
  
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body
        className={`${inter.className} antialiased`} suppressHydrationWarning={true}
      >
        <NextIntlClientProvider messages= {messages}>
          <Header />
          <Subheader />
          {tquery === ''? (
            <main>{children}</main>
          ):(
            <div className="max-w-screen-xl w-full mx-auto md:w-3/4 mt-1 bg-white p-4 ">
              <SearchContent tagquery={tquery} tagcurrentPage= {tcurrentPage} />
              <div className='mt-12 flex justify-center'>
                <Pagination totalPages={totalPages} />
              </div>
            </div>
          )}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
